# Setup
title:               Radical Periodical Index
tagline:             'The Alarm'
description:         'This is a GitHub edition of the [Radical Periodical Index](radicalperiodicalindex.com).'
url:                 https://mrileysoriano.github.io/lanyonexample
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Michael Soriano
  url:               
  email:             mrs319@miami.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
